add context in amqp for dynamic routing
nautiluslabsco/ergo pull request #47
Opened 2021-11-30 22:52 UTC by zekenautilus

2021-11-30 22:58 UTC, zekenautilus commented on src/function_invocable.py
> +    def invoke(self, data_in: TYPE_PAYLOAD, context) -> Generator[TYPE_PAYLOAD, TYPE_PAYLOAD, None]:
can default to None so that context is not needed

2021-12-01 03:39 UTC, mattian7741 commented
Zeke - perhaps you, Ricky and I can jump on a call to discuss this.   Ricky has a specific need for dynamic routing with the work that he is doing on DPI, so he is already working on a solution with my help.   It is similar to what you are proposing here except that it isn't doesn't impose as strong constraints on the function signature.

In effect, the key difference is that context is the first parameter, rather than the last.   And the component configuration yaml provides a signal to ergo that the injected function takes a context.   This signal must be explicit in configuration because we are otherwise forced into an ergo-specific contract.

Perhaps you could join my sync with Ricky tomorrow @ 10:15.   I will add you.

2021-12-01 14:48 UTC, ahuman-bean commented on src/function_invocable.py
> +            context (Dict): Passes along additional context
Should make context a typed object, since its fields are more interesting to document

2021-12-01 14:50 UTC, ahuman-bean commented on src/amqp_invoker.py
> +                yield {'data': data_out, 'key': context_out['pubtopic'], 'log': data_in.get('log', [])}
I'd rather the provided context object be mutable, than to have to return it explicitly.

2021-12-01 14:52 UTC, ahuman-bean commented on src/function_invocable.py
> +                result = self._func(data_in)
somewhat hidden within this change is that fact that we're no longing spreading out `data` correct?

2021-12-01 14:54 UTC, ahuman-bean commented
> Zeke - perhaps you, Ricky and I can jump on a call to discuss this. Ricky has a specific need for dynamic routing with the work that he is doing on DPI, so he is already working on a solution with my help. It is similar to what you are proposing here except that it isn't doesn't impose as strong constraints on the function signature.
> 
> In effect, the key difference is that context is the first parameter, rather than the last. And the component configuration yaml provides a signal to ergo that the injected function takes a context. This signal must be explicit in configuration because we are otherwise forced into an ergo-specific contract.
> 
> Perhaps you could join my sync with Ricky tomorrow @ 10:15. I will add you.

The placement of `context` in the function signature won't matter if we're leveraging runtime type inspection to provide it anyways

2021-12-01 19:21 UTC, zekenautilus commented on src/amqp_invoker.py
> +                yield _data_out, curr_context
can put some of the context logic in function_invocable if that makes more sense? And switch in here on if we get data_out, and context, or just data_out.

2021-12-07 14:39 UTC, zekenautilus commented
@ahuman-bean @mattian7741 updated s.t. it matches based on type and filters keywords.

So something like:
```
from src.types import ErgoContext
def zeke_product(dumb_context_name: ErgoContext, x: int, y: int)
    if x % 2 == 0:
        dumb_context_name['pubtopic'] = 'sum'
        return x + y
    return x * y
```

will work as expected (`dumb_context_name`'s position, nor its name matter - we match on the type annotation!) and additionally work if the data payload has additional keys.

For example, publishing:
```
{"data": {"x": 2, "y": 3, "z": 5}}
```
expectedly results in 5 w routing key `sum`!

2021-12-07 18:49 UTC, zekenautilus commented on src/types.py
> +ErgoContext = Dict
not super sure what to put in this class atm. So thinking it's best to alias as Dict for now, until a use case pops up where we might want to promote it from a type alias to its own class.

2021-12-07 18:52 UTC, ahuman-bean commented on src/types.py
> +ErgoContext = Dict
changes to this would be breaking

if we're already committing to allowing `pubtopic`, this could easily just be a dataclass w/ `pubtopic` as a field

using a `Dict` right from the get-go could result in minor versioning annoyances

2021-12-07 19:38 UTC, zekenautilus commented on src/types.py
> +ErgoContext = Dict
It def requires more thought... also i'm not the biggest fan of this currently being export as `src.util.ErgoContext`. it should probably be `ergo.types.ErgoContext`

Also, updating it to be a class that's used across invokers (so not just the amqp invoker) makes it a little weird to include things in the context that are amqp specific (like pubtopic). But at the same time, we already have `pubtopic` at the global level of the config so maybe that's a field that should be consumable by all invokers...

2021-12-07 20:58 UTC, zekenautilus commented on src/types.py
> +ErgoContext = Dict
also another can of worms... should we have invoker specific contexts? Can / should we support passing along any of them to a specific function? ... i.e. instead of `ErgoContext` we pass along `ErgoAmqpContext` which has AMQP specific info (`routing_key` and `exchange`) and maybe a `ErgoHttpContext` which was HTTP specific info (`endpoint` `host)...

2021-12-07 21:35 UTC, zekenautilus commented on src/types.py
> +ErgoContext = Dict
@ahuman-bean updated! still working through my mind, lmk what you think.

2021-12-07 21:40 UTC, ahuman-bean commented on src/types.py
> +ErgoContext = Dict
Then I think it's better to make `Context` an interface and turn `pubtopic` into a concept rather than something concrete. E.g. for HTTP or Console apps, it could be unimplemented and therefore unused.

2021-12-08 15:55 UTC, zekenautilus commented on src/types.py
> +ErgoContext = Dict
I think that's a solid idea. Maybe can be punted on as follow up work? I.e. revisiting what the pubtopic interface is, and so on in the config, and in turn updating the Context to being an interface.

2021-12-08 19:11 UTC, zekenautilus commented on setup.py
> +        'yarl'
this `yarl` package is driving me insane... thought it would get picked up by `aio-pika` since it's a dependency for that... but when dev'ing locally as a consumer of ergo i always end up having to install it in my virtualenv

2021-12-10 16:19 UTC, mattian7741 requested changes
I am going to look at this in further detail over the weekend and provide a comprehensive response next week.  But this should not be merged as it is.

2021-12-22 15:00 UTC, closed without merging